export const agentProfile = {
  name: 'Amirah Yusof',
  title: 'Senior Insurance Advisor',
  avatar: 'https://i.pravatar.cc/150?u=amirah',
  clientsCount: 4,
  renewalAlerts: 2,
};

export const mockClients = [
  {
    id: 'c1',
    name: 'Sarah Chen',
    age: 34,
    avatar: 'https://i.pravatar.cc/150?u=sarah',
    policyStatus: 'Active',
    relationshipStage: 'Upsell Candidate',
    riskTier: 'Low',
    nextAction: 'Cross-sell Life Insurance',
    urgency: 'Medium',
    lifeEvents: [
      { label: 'Recently Married', icon: 'ring', time: '2 mos ago' },
      { label: 'Promoted to Director', icon: 'briefcase', time: '1 mo ago' },
    ],
    medicalRisk: {
      score: 12,
      summary: 'Excellent health. Non-smoker, active lifestyle, no family history of chronic illness.',
      factors: ['Non-smoker', 'BMI 21', 'Active (5×/wk)', 'No family history'],
    },
    personality: {
      type: 'Conscientiousness (C)',
      disc: 'C',
      description: 'Analytical, data-driven, and risk-averse. Needs proof before making decisions.',
      traits: ['Detail-oriented', 'Needs proof', 'Slow decision maker', 'Risk-averse'],
      dos: ['Provide data & comparison charts', 'Use empirical evidence', 'Give time to review', 'Send detailed reports'],
      donts: ["Don't rush or pressure", "Avoid vague promises", "Don't skip details", "Never use emotional appeals alone"],
      sampleOpener: "Sarah, I've run a full actuarial comparison on three term-life structures based on your current financial profile. Would you like me to send the breakdown so you can review the numbers at your own pace?",
      approach: 'Lead with data and comparisons. Provide charts. Do not rush. Give ample time for deliberation.',
      confidenceScore: 91,
    },
    recommendation: {
      planName: 'Comprehensive Term Life + Critical Illness',
      premiumRange: 'RM 250 – 350 / month',
      currentCoverage: 0,
      recommendedCoverage: 1500000,
      riders: ['Critical Illness Rider', 'Waiver of Premium', 'Personal Accident'],
      coverageGap: 'Currently unprotected — new marital dependency risk identified.',
      rationale: 'Recent marriage increases financial dependency risk. Current medical profile qualifies for preferred (lowest) premium rates. Life-stage event triggers standard coverage recommendation.',
      xaiFactors: ['Recently Married', 'Age 34', 'Low Medical Risk (12/100)', 'No existing life cover'],
      comparison: '+RM 1.5M coverage vs current RM 0',
    },
    coaching: {
      channel: 'Email',
      channelIcon: 'mail',
      timing: 'Tuesday 9–11 AM (High open rate)',
      script: "Hi Sarah, based on your recent marriage milestone, I've run some projections on how a Term Life policy fits into your long-term financial architecture. I've attached a comparison matrix showing the RM 1.5M coverage options across three carriers. Let me know when you've had time to review the data — no rush at all.",
      nextTouchpoint: { date: '2026-07-01', label: 'Follow-up email — data review check-in' },
      objectionHandling: [
        {
          objection: 'I need more time to research.',
          response: "Absolutely. Take your time. Would it help if I sent over the independent rating reports for these carriers so you have objective data to compare?",
        },
        {
          objection: "The premium seems high.",
          response: "Totally fair. Let me show you a tiered breakdown — there's a lower-entry option at RM 250/month that still covers the critical illness component fully.",
        },
      ],
    },
    notifications: [
      { id: 'n1', message: 'Cross-sell opportunity flagged — new marriage life event', urgency: 'Medium', time: '2h ago' },
    ],
  },
  {
    id: 'c2',
    name: 'Ahmad Faiz',
    age: 42,
    avatar: 'https://i.pravatar.cc/150?u=ahmad',
    policyStatus: 'Renewal Due',
    relationshipStage: 'Renewal',
    riskTier: 'High',
    nextAction: 'Renewal & Plan Restructure',
    urgency: 'High',
    lifeEvents: [
      { label: 'Purchased New Property', icon: 'home', time: '6 mos ago' },
      { label: 'Diagnosed: Mild Hypertension', icon: 'heart', time: '3 mos ago' },
    ],
    medicalRisk: {
      score: 75,
      summary: 'Elevated risk: recent hypertension diagnosis, family cardiac history, slightly elevated BMI.',
      factors: ['Hypertension (Stage 1)', 'BMI 28', 'Family Hx: Cardio', 'Age 42'],
    },
    personality: {
      type: 'Dominance (D)',
      disc: 'D',
      description: 'Direct, results-oriented, fast decision maker. Values efficiency above all else.',
      traits: ['Impatient', 'Bottom-line focused', 'Decisive', 'Values ROI'],
      dos: ['Be concise and direct', 'Present 2–3 clear options', 'Focus on ROI and outcomes', 'Show immediate value'],
      donts: ["Don't over-explain", "Avoid lengthy small talk", "Don't give 10 options", "Never be vague about cost"],
      sampleOpener: "Ahmad, your policy renewal is in 14 days and with the hypertension update, we need to lock in rates now. I have two structured options — one protects your property loan exposure. Can we do 5 minutes today?",
      approach: 'Be direct. Focus on ROI and immediate problem-solving. Give a maximum of 3 options to choose from.',
      confidenceScore: 88,
    },
    recommendation: {
      planName: 'Medical Upgrade + Premium Waiver Rider',
      premiumRange: 'RM 450 – 550 / month',
      currentCoverage: 500000,
      recommendedCoverage: 1200000,
      riders: ['Premium Waiver Rider', 'Hypertension Exclusion Review', 'Mortgage Reducing Term Assurance'],
      coverageGap: 'Property loan exposure (RM 850K) exceeds current life coverage by RM 350K.',
      rationale: 'Hypertension diagnosis indicates need to lock in current rates before condition progresses. Property purchase increases debt exposure requiring higher sum assured. Delaying risks coverage unavailability.',
      xaiFactors: ['Age 42', 'Hypertension (Stage 1)', 'Family Cardiac Hx', 'RM 850K Property Debt'],
      comparison: 'Adds premium waiver + higher annual limit (RM 500K → RM 1.2M)',
    },
    coaching: {
      channel: 'WhatsApp',
      channelIcon: 'message-square',
      timing: 'Immediately (High urgency)',
      script: "Ahmad, your medical renewal is coming up in 14 days. With the recent hypertension update, we need to restructure your plan to lock in rates now before premiums jump. I have two options ready. Let's do a 5-min call today at 4 PM to finalize.",
      nextTouchpoint: { date: '2026-06-27', label: 'Urgent call — policy restructure decision' },
      objectionHandling: [
        {
          objection: 'The premium is too high.',
          response: "The cost of waiting is higher. If your condition progresses to Stage 2, this coverage will be unavailable at any price. We lock this in today to protect your assets.",
        },
        {
          objection: "I'll think about it.",
          response: "I understand — but the renewal window closes in 14 days. After that, a new medical assessment is required and current rates cannot be guaranteed. I can hold the quote until Friday.",
        },
      ],
    },
    notifications: [
      { id: 'n2', message: 'URGENT: Renewal due in 14 days — high medical risk client', urgency: 'High', time: '30m ago' },
      { id: 'n3', message: 'Medical risk score updated: 68 → 75 after new diagnosis', urgency: 'High', time: '3d ago' },
    ],
  },
  {
    id: 'c3',
    name: 'Emily Tan',
    age: 28,
    avatar: 'https://i.pravatar.cc/150?u=emily',
    policyStatus: 'Prospect',
    relationshipStage: 'New Prospect',
    riskTier: 'Medium',
    nextAction: 'First Appointment',
    urgency: 'Low',
    lifeEvents: [
      { label: 'Started First Business', icon: 'briefcase', time: '4 mos ago' },
    ],
    medicalRisk: {
      score: 35,
      summary: 'Moderate risk. Vapes occasionally, high-stress occupation. Otherwise healthy baseline.',
      factors: ['Occasional Vaper', 'High Stress (Entrepreneur)', 'BMI 22', 'Age 28'],
    },
    personality: {
      type: 'Influence (I)',
      disc: 'I',
      description: 'Social, relationship-driven, and enthusiastic. Builds trust through connection.',
      traits: ['Talkative', 'Values relationships', 'Emotionally driven', 'Optimistic'],
      dos: ['Build rapport first', 'Share client success stories', 'Keep it visionary and inspiring', 'Invite to events or coffee'],
      donts: ["Don't lead with dense data", "Avoid cold formal language", "Don't rush to close", "Never ignore their emotions"],
      sampleOpener: "Hey Emily! Congrats again on the business! I'd love to grab coffee and hear all about it. I also have some cool ideas other founders in my network are using to protect their ventures — are you free Friday?",
      approach: 'Build genuine rapport first. Share stories and testimonials. Keep it light, warm, and visionary.',
      confidenceScore: 84,
    },
    recommendation: {
      planName: 'Investment-Linked Policy (ILP)',
      premiumRange: 'RM 200 – 300 / month',
      currentCoverage: 0,
      recommendedCoverage: 500000,
      riders: ['Personal Accident Rider', 'Critical Illness (Basic)', 'Business Protection Add-on'],
      coverageGap: 'No business continuity protection — founder risk unmitigated.',
      rationale: 'Young entrepreneur needing flexible premiums and wealth accumulation alongside basic protection. ILP allows premium adjustment as business cash flow varies.',
      xaiFactors: ['Age 28', 'Entrepreneur (Variable Income)', 'No Existing Coverage', 'Medium Risk (35/100)'],
      comparison: 'New policy — RM 500K protection + investment component',
    },
    coaching: {
      channel: 'Coffee Meeting',
      channelIcon: 'coffee',
      timing: 'Friday 3–5 PM (preferred social window)',
      script: "Hey Emily! Congrats again on the new business! I'd love to grab coffee this week to hear all about it. I also have some cool ideas on how other founders in my network are setting up their financial safety nets. Are you free Friday at 3?",
      nextTouchpoint: { date: '2026-06-28', label: 'Coffee catch-up — first consultation' },
      objectionHandling: [
        {
          objection: "I don't have the budget right now.",
          response: "Totally get it — launching a business is intense! We don't have to commit to anything today. I just want to show you what's possible so you have a roadmap for when the time is right.",
        },
        {
          objection: "Insurance feels boring.",
          response: "Ha — fair! But here's the thing: the founders who scale fastest are the ones who protect downside risk early. I'll show you how two of my clients used ILPs to fund their next business round.",
        },
      ],
    },
    notifications: [
      { id: 'n4', message: 'First appointment scheduled — Emily Tan (Friday 3 PM)', urgency: 'Low', time: '1d ago' },
    ],
  },
  {
    id: 'c4',
    name: 'Raj Patel',
    age: 50,
    avatar: 'https://i.pravatar.cc/150?u=raj',
    policyStatus: 'Policy Holder',
    relationshipStage: 'Policy Holder',
    riskTier: 'Medium',
    nextAction: 'Annual Review & Upsell',
    urgency: 'Medium',
    lifeEvents: [
      { label: 'Child Started University', icon: 'graduation', time: '2 mos ago' },
      { label: 'Approaching Retirement (10 yrs)', icon: 'calendar', time: 'Upcoming' },
    ],
    medicalRisk: {
      score: 52,
      summary: 'Average risk for age bracket. Controlled diabetes, physically active. Family history of stroke.',
      factors: ['Type 2 Diabetes (Controlled)', 'BMI 25', 'Family Hx: Stroke', 'Age 50'],
    },
    personality: {
      type: 'Steadiness (S)',
      disc: 'S',
      description: 'Reserved, loyal, and deeply risk-averse. Values stability, relationships, and long-term security.',
      traits: ['Patient', 'Loyal', 'Dislikes change', 'Security-focused'],
      dos: ['Lead with security & stability', 'Share testimonials from similar clients', 'Allow plenty of decision time', 'Emphasise long-term benefits'],
      donts: ["Don't apply pressure", "Avoid sudden or large changes", "Don't dismiss concerns", "Never rush to a decision"],
      sampleOpener: "Raj, it's been a year since we last reviewed your portfolio. With your daughter starting university and retirement on the 10-year horizon, I'd love to sit down and make sure your coverage still aligns with your family's future. When suits you best?",
      approach: 'Lead with security and long-term protection. Avoid high-pressure tactics. Allow time for deliberation.',
      confidenceScore: 79,
    },
    recommendation: {
      planName: 'Retirement Income Plan + Medical Enhancement',
      premiumRange: 'RM 380 – 480 / month',
      currentCoverage: 750000,
      recommendedCoverage: 1100000,
      riders: ['Retirement Income Rider', 'Stroke & Cardiovascular Rider', 'Extended Medical (RM 200K limit)'],
      coverageGap: 'Retirement income gap estimated at RM 2K/month. Stroke risk under-covered.',
      rationale: "Age 50 marks the critical window to lock in retirement income protection. Family stroke history creates an underinsured risk for cerebrovascular events. Child's university cost adds short-term liquidity pressure.",
      xaiFactors: ['Age 50', 'Controlled Diabetes', 'Family Stroke Hx', '10-yr Retirement Horizon'],
      comparison: 'Upgrades coverage RM 750K → RM 1.1M + retirement income stream',
    },
    coaching: {
      channel: 'Phone Call',
      channelIcon: 'phone',
      timing: 'Saturday 10–11 AM (family time — relaxed)',
      script: "Hi Raj, it's been a year since we last sat down and I just want to make sure your family is still fully covered as things change. With Maya starting university and the 10-year retirement milestone coming up, a quick annual review would give you real peace of mind. Would Saturday morning work for a call?",
      nextTouchpoint: { date: '2026-06-29', label: 'Annual review call — retirement planning' },
      objectionHandling: [
        {
          objection: "I'm happy with my current plan.",
          response: "That's wonderful to hear — it means we've built a solid foundation together. The review is just to make sure it still fits your life as things evolve. Takes only 30 minutes and you'll leave with complete peace of mind.",
        },
        {
          objection: "I need to discuss with my family first.",
          response: "Absolutely — that's the right approach. Would it help if I prepared a simple family summary document you could share with them before we speak? That way everyone's on the same page.",
        },
      ],
    },
    notifications: [
      { id: 'n5', message: 'Annual review overdue by 3 weeks — Raj Patel', urgency: 'Medium', time: '3d ago' },
    ],
  },
];
